# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\meles\Desktop\LabWork_GUI\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 381, 131))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.button_click)
        self.pushButton.setFont(font)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 150, 371, 431))        
        self.label.setFont(font)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def button_click(self):
            films = [
                        "1. Властелин колец 3: Возвращение Короля (The Lord of the Rings: The Return of the King), 2003",
                        "2. Терминатор 2: Судный день (Terminator 2: Judgment Day), 1991",
                        "3. Побег из Шоушенка (The Shawshank Redemption), 1994",
                        "4. Форрест Гамп (Forrest Gump), 1994",
                        "5. Властелин колец 2: Две крепости (The Lord of the Rings: The Two Towers), 2002",
                        "6. Старики-разбойники, 1971",
                        "7. Холодное лето пятьдесят третьего, 1987",
                        "8. Здравствуйте, я ваша тетя!, 1975",
                        "9. Властелин колец: Братство кольца (The Lord of the Rings: The Fellowship of the Ring), 2001",
                        "10. Они сражались за Родину, 1975",
                        "11. Титаник (Titanic), 1997",
                        "12. Список Шиндлера (Schindler`s List), 1993",
                        "13. Настоящая любовь (True Romance), 1993",
                        "14. 12 разгневанных мужчин (12 Angry Men), 1957",
                        "15. Зеленая миля (The Green Mile), 1999",
                        "16. Крестный отец (The Godfather), 1972",
                        "17. Матрица (The Matrix), 1999",
                        "18. Шерлок Холмс и доктор Ватсон: Собака Баскервилей, 1981",
                        "19. Шерлок Холмс и доктор Ватсон: Охота на тигра, 1980",
                        "20. Назад в будущее (Back to the Future), 1985",
                        "21. Иван Васильевич меняет профессию, 1973",
                        "22. Кавказская пленница, или новые приключения Шурика, 1966",
                        "23. Шерлок Холмс и доктор Ватсон: Знакомство, 1979",
                        "24. Темный рыцарь (The Dark Knight), 2008",
                        "25. Гладиатор (Gladiator), 2000",
                        "26. Пролетая над гнездом кукушки (One Flew Over the Cuckoo`s Nest), 1975",
                        "27. Храброе сердце (Braveheart), 1995",
                        "28. Бриллиантовая рука, 1968",
                        "29. Молчание ягнят (The Silence of the Lambs), 1991",
                        "30. Чужие (Aliens), 1986",
                        "31. Джентльмены удачи, 1971",
                        "32. Аватар (Avatar), 2009",
                        "33. Пираты Карибского моря: Проклятие Черной жемчужины (Pirates of the ",
                        "34. Назад в будущее 2 (Back to the Future Part II), 1989",
                        "35. В бой идут одни старики, 1973",
                        "36. Шерлок Холмс и доктор Ватсон: Кровавая надпись, 1979",
                        "37. Начало (Inception), 2010",
                        "38. 1+1 (The Intouchables), 2011",
                        "39. Мстители 3: Война бесконечности (Avengers: Infinity War), 2018",
                        "40. Мимино, 1977",
                        "41. Собака на сене, 1977",
                        "42. Терминатор (The Terminator), 1984",
                        "43. Король - рыбак (The Fisher King), 1991",
                        "44. Леон (Léon), 1994",
                        "45. Бен-Гур (Ben-Hur), 1959",
                        "46. День сурка (Groundhog Day), 1993",
                        "47. Хороший, плохой, злой (The Good, the Bad and the Ugly), 1966",
                        "48. Операция Ы и другие приключения Шурика, 1965",
                        "49. Римские каникулы (Roman Holiday), 1953",
                        "50. Ребенок Розмари (Rosemary`s Baby), 1968",
                        "51. Шерлок Холмс и доктор Ватсон: Король шантажа, 1980",
                        "52. Криминальное чтиво (Pulp Fiction), 1994",
                        "53. Крестный отец 2 (The Godfather: Part II), 1974",
                        "54. Десять негритят, 1987",
                        "55. Парк Юрского периода (Jurassic Park), 1993",
                        "56. Москва слезам не верит, 1979",
                        "57. Пес Барбос и необычный кросс, 1961",
                        "58. Заплати другому (Pay It Forward), 2000",
                        "59. Жестокий романс, 1984",
                        "60. Один дома (Home Alone), 1990",
                        "61. Блеф (Bluff storia di truffe e di imbroglioni), 1976",
                        "62. Назад в будущее 3 (Back to the Future Part III), 1990",
                        "63. А зори здесь тихие, 1972",
                        "64. Экипаж, 1979",
                        "65. Человек-слон (The Elephant Man), 1980",
                        "66. Семь (Se7en), 1995",
                        "67. Укрощение строптивого (Il bisbetico domato), 1980",
                        "68. Гран Торино (Gran Torino), 2008",
                        "69. Тот самый Мюнхгаузен, 1979",
                        "70. Лоуренс Аравийский (Lawrence of Arabia), 1962",
                        "71. Спасти рядового Райана (Saving Private Ryan), 1998",
                        "72. Однажды в Америке (Once Upon a Time in America), 1984",
                        "73. Меня зовут Кхан (My Name Is Khan), 2010",
                        "74. Свой среди чужих, чужой среди своих, 1974",
                        "75. Пираты Карибского моря 2: Сундук мертвеца (Pirates of the Caribbean: Dead Man`s Chest), 2006",
                        "76. Унесенные ветром (Gone with the Wind), 1939",
                        "77. Путь Карлито (Carlito`s Way), 1993",
                        "78. Бойцовский клуб (Fight Club), 1999",
                        "79. Хищник (Predator), 1987",
                        "80. Чужой (Alien), 1979",
                        "81. Берегись автомобиля, 1966",
                        "82. Профессионал (The Professional), 1981",
                        "83. Звездные войны: Эпизод 5 - Империя наносит ответный удар (Star Wars: Episode V - The Empire Strikes Back), 1980",
                        "84. Взвод (Platoon), 1986",
                        "85. Казино (Casino), 1995",
                        "86. Жизнь прекрасна (La Vita è bella), 1997",
                        "87. На несколько долларов больше (For a Few Dollars More), 1965",
                        "88. Тутси (Tootsie), 1982",
                        "89. Переговорщик (The Negotiator), 1998",
                        "90. Не может быть!, 1975",
                        "91. Изгой (Cast Away), 2000",
                        "92. Малышка на миллион (Million Dollar Baby), 2004",
                        "93. Невероятные приключения итальянцев в России, 1973",
                        "94. Покровские ворота, 1982",
                        "95. Индиана Джонс и последний крестовый поход (Indiana Jones and the Last Crusade), 1989",
                        "96. Апокалипсис сегодня (Apocalypse Now), 1979",
                        "97. Смертельное оружие (Lethal Weapon), 1987",
                        "98. Самогонщики, 1961",
                        "99. Завтрак у Тиффани (Breakfast at Tiffany`s), 1961",
                        "100. Отступники (The Departed), 2006"
                    ]       
            i = np.random.randint(0, 99)            
            self.label.setText(films[i])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Загадать фильм"))
        self.pushButton.setText(_translate("MainWindow", "Крутите барабан!"))
